#docker network create --driver bridge rossmann-network
#docker network inspect rossmann-network

networks:
  rossmann-network:
    external: true

services:    
  local_db_1:
    container_name: offline-market-db-1
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 2000:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
        interval: 10s
        timeout: 10s
        retries: 12

  local_db_2:
    container_name: offline-market-db-2
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 2001:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
        interval: 10s
        timeout: 10s
        retries: 12

  local_db_3:
    container_name: offline-market-db-3
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 2002:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
        interval: 10s
        timeout: 10s
        retries: 12

  local_db_4:
    container_name: offline-market-db-4
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 2003:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
        interval: 10s
        timeout: 10s
        retries: 12

  local_db_5:
    container_name: offline-market-db-5
    networks:
      - rossmann-network
    image: postgres:latest
    restart: always
    ports:
      - 2004:5432
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER"]
        interval: 10s
        timeout: 10s
        retries: 12

  local_app_1:
    container_name: offline-market-app-1
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      local_db_1:
        condition: service_healthy
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: local_db_1
      SHOP_ID: 1
      ADMIN_EMAIL: 'stannis.baratheon@example.com'
      COURIER_EMAIL: 'ramsay.bolton@example.com'
      CASHIER_1_EMAIL: 'renly.baratheon@example.com'
      CASHIER_2_EMAIL: 'davos.seaworth@example.com'
      CASHIER_3_EMAIL: 'robert.baratheon@example.com'
    restart: on-failure:3


  local_app_2:
    container_name: offline-market-app-2
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      local_db_2:
        condition: service_healthy
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: local_db_2
      SHOP_ID: 2
      ADMIN_EMAIL: 'eddard.stark@example.com'
      COURIER_EMAIL: 'ramsay.bolton@example.com'
      CASHIER_1_EMAIL: 'robb.stark@example.com'
      CASHIER_2_EMAIL: 'jon.snow@example.com'
      CASHIER_3_EMAIL: 'catelyn.stark@example.com'
    restart: on-failure:3

  local_app_3:
    container_name: offline-market-app-3
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      local_db_3:
        condition: service_healthy
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: local_db_3
      SHOP_ID: 3
      ADMIN_EMAIL: 'tywin.lannister@example.com'
      COURIER_EMAIL: 'ramsay.bolton@example.com'
      CASHIER_1_EMAIL: 'tyrion.lannister@example.com'
      CASHIER_2_EMAIL: 'jaime.lannister@example.com'
      CASHIER_3_EMAIL: 'cersei.lannister@example.com'
    restart: on-failure:3

  local_app_4:
    container_name: offline-market-app-4
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      local_db_4:
        condition: service_healthy
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: local_db_4
      SHOP_ID: 4
      ADMIN_EMAIL: 'petyr.baelish@example.com'
      COURIER_EMAIL: 'ramsay.bolton@example.com'
      CASHIER_1_EMAIL: 'brienne.tarth@example.com'
      CASHIER_2_EMAIL: 'jorah.mormont@example.com'
      CASHIER_3_EMAIL: 'theon.greyjoy@example.com'
    restart: on-failure:3

  local_app_5:
    container_name: offline-market-app-5
    networks:
      - rossmann-network
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    depends_on:
      local_db_5:
        condition: service_healthy
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_HOST: local_db_5
      SHOP_ID: 5
      ADMIN_EMAIL: 'samwell.tarly@example.com'
      COURIER_EMAIL: 'ramsay.bolton@example.com'
      CASHIER_1_EMAIL: 'bronn.blackwater@example.com'
      CASHIER_2_EMAIL: 'sandor.clegane@example.com'
      CASHIER_3_EMAIL: 'gendry.waters@example.com'
    restart: on-failure:3
