from dotenv import load_dotenv
import os

load_dotenv()

DATE_TIME_FORMAT = os.getenv("DATE_TIME_FORMAT", "%Y-%m-%d %H:%M:%S") 

POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB = os.getenv("POSTGRES_DB")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")

OLTP_API_HOST = os.getenv("OLTP_API_HOST")
OLTP_API_PORT = os.getenv("OLTP_API_PORT")

KAFKA_HOST = os.getenv("KAFKA_HOST")
KAFKA_PORT = os.getenv("KAFKA_PORT")
KAFKA_TOPIC_OLTP_UPDATE_PRODUCT_QUANTITY = os.getenv("KAFKA_TOPIC_OLTP_UPDATE_PRODUCT_QUANTITY")
KAFKA_TOPIC_LOCAL_DB_UPSERT_CATEGORY = os.getenv("KAFKA_TOPIC_LOCAL_DB_UPSERT_CATEGORY")

MINIO_HOST = os.getenv("MINIO_HOST")
MINIO_PORT = os.getenv("MINIO_PORT")
MINIO_ACCESS_KEY = os.getenv("MINIO_ACCESS_KEY")
MINIO_SECRET_KEY = os.getenv("MINIO_SECRET_KEY")

SHOP_ID = os.getenv('SHOP_ID')
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL')
COURIER_EMAIL = os.getenv('COURIER_EMAIL')
CASHIER_1_EMAIL = os.getenv('CASHIER_1_EMAIL')
CASHIER_2_EMAIL = os.getenv('CASHIER_2_EMAIL')
CASHIER_3_EMAIL = os.getenv('CASHIER_3_EMAIL')